services:
  db:
    image: postgres:16
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=teste
    restart: "on-failure"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d password'"]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "5432:5432"